version: '3'

services:

  admin:
    image: harbor.nanjiren.online:8099/aichat/aichat-admin:latest
    container_name: aichat-admin
    restart: always
    depends_on:
      - db
      - redis
      - util
    environment:
      DB_URL: jdbc:mysql://aichat-db:3306/aichat?useSSL=false
      DB_USERNAME: root
      DB_PASSWORD: n0Ght7cDun4AItGaichat
      REDIS_HOST: aichat-redis
      REDIS_PORT: 6379
      SUPERADMIN_USERNAME: aichat
      SUPERADMIN_PASSWORD: aichatadmin
      PASSWORD_SALT: any-is-ok
      DEFAULT_TOKENS: 3000
      DEFAULT_CHAT_COUNT: 20
      DEFAULT_ADVANCED_CHAT_COUNT: 2
      DEFAULT_DRAW_COUNT: 0
      MAIL_HOST: smtp.qq.com
      MAIL_PORT: 25
      MAIL_USERNAME: your-email-username
      MAIL_PASSWORD: your-email-password
      TZ: Asia/Shanghai
      LICENSE_SUBJECT: qq@qq.com
      LICENSE_SK: your-sk-please-get-from-http://console.nanjiren.online
      UTIL_ENDPOINT: http://aichat-util:7788
      STORE_TYPE:
      OSS_ENDPOINT:
      OSS_BUCKET_NAME:
      OSS_ACCESS_KEY_ID:
      OSS_ACCESS_KEY_SECRET:
    ports:
      - "8082:8080"

  web:
    image: nanjiren01/aichat-web:pro-latest
    container_name: aichat-web
    restart: always
    depends_on:
      - admin
    ports:
      - "80:3000"
    environment:
      BASE_URL: http://aichat-admin:8080
      TZ: Asia/Shanghai

  console:
    image: nanjiren01/aichat-console:pro-latest
    container_name: aichat-console
    restart: always
    depends_on:
      - admin
    ports:
      - "8080:80"
    environment:
      TZ: Asia/Shanghai

  db:
    image: nanjiren01/aichat-db:latest
    container_name: aichat-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: n0Ght7cDun4AItGaichat
      TZ: Asia/Shanghai
    # ports:
    #   - "3310:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis:
    image: nanjiren01/aichat-redis:latest
    container_name: aichat-redis
    restart: always
  #    ports:
  #      - "6380:6379"

  util:
    image: harbor.nanjiren.online:8099/aichat/aichat-util:latest
    container_name: aichat-util
    restart: always
    network_mode: host
    environment:
      PORT: 7788
      TZ: Asia/Shanghai
#    ports:
#      - "7788:7788"
